platform :ios, '13.0'
pod 'IronSourceSDK','8.2.0.0'
pod 'IronSourceAdQualitySDK','7.20.3'


{{#iron_source.applovin_ios}}
pod 'IronSourceAppLovinAdapter','4.3.47.2'
{{/iron_source.applovin_ios}}

{{#iron_source.aps_ios}}
pod 'IronSourceAPSAdapter','4.3.15.0'
{{/iron_source.aps_ios}}

{{#iron_source.bidmachine_ios}}
pod 'IronSourceBidMachineAdapter','4.3.10.0'
{{/iron_source.bidmachine_ios}}

{{#iron_source.charboost_ios}}
pod 'IronSourceChartboostAdapter','4.3.19.1'
{{/iron_source.charboost_ios}}

{{#iron_source.csj_ios}}
pod 'IronSourceCSJAdapter', '4.3.4.0'
{{/iron_source.csj_ios}}

{{#iron_source.dt_exchange_ios}}
pod 'IronSourceFyberAdapter','4.3.36.1'
{{/iron_source.dt_exchange_ios}}

{{#iron_source.facebook_ios}}
pod 'IronSourceFacebookAdapter','4.3.45.2'
{{/iron_source.facebook_ios}}

{{#iron_source.admob_ios}}
pod 'IronSourceAdMobAdapter','4.3.56.0'
{{/iron_source.admob_ios}}

{{#iron_source.hyprmx_ios}}
pod 'IronSourceHyprMXAdapter','4.3.5.4'
{{/iron_source.hyprmx_ios}}

{{#iron_source.inmobi_ios}}
pod 'IronSourceInMobiAdapter','4.3.24.0'
{{/iron_source.inmobi_ios}}

{{#iron_source.liftoff_ios}}
pod 'IronSourceVungleAdapter','4.3.36.0'
{{/iron_source.liftoff_ios}}

{{#iron_source.maio_ios}}
pod 'IronSourceMaioAdapter','4.1.11.13'
{{/iron_source.maio_ios}}

{{#iron_source.mintegral_ios}}
pod 'IronSourceMintegralAdapter', '4.3.25.0'
{{/iron_source.mintegral_ios}}

{{#iron_source.moloco_ios}}
pod 'IronSourceMolocoAdapter','4.3.4.0'
{{/iron_source.moloco_ios}}

{{#iron_source.mytarget_ios}}
pod 'IronSourceMyTargetAdapter','4.1.23.0'
{{/iron_source.mytarget_ios}}

{{#iron_source.pangle_ios}}
pod 'IronSourcePangleAdapter','4.3.29.0'
{{/iron_source.pangle_ios}}

{{#iron_source.smaato_ios}}
pod 'IronSourceSmaatoAdapter','4.3.13.5'
{{/iron_source.smaato_ios}}

{{#iron_source.superawesome_ios}}
pod 'IronSourceSuperAwesomeAdapter','4.1.12.2'
{{/iron_source.superawesome_ios}}

{{#iron_source.tencent_ios}}
pod 'IronSourceTencentAdapter','4.3.7.0'
{{/iron_source.tencent_ios}}

{{#iron_source.unityads_ios}}
pod 'IronSourceUnityAdsAdapter','4.3.42.0'
{{/iron_source.unityads_ios}}

{{#iron_source.yandex_ads_ios}}
pod 'IronSourceYandexAdapter', '4.3.3.0'
{{/iron_source.yandex_ads_ios}}

