#!/usr/bin/env python3

"""Generate and validate the Defold Android LevelPlay manifests."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Sequence

from common import (
    ANDROID_KEYS,
    DEFAULT_EXTENSION_DIR,
    MAVEN_CENTRAL,
    UpdaterError,
    dependency_repository,
    load_catalog,
    maven_versions,
    parse_coordinate,
    write_or_check,
)


DEFAULT_GRADLE = DEFAULT_EXTENSION_DIR / "manifests/android/build.gradle"
DEFAULT_MANIFEST = DEFAULT_EXTENSION_DIR / "manifests/android/AndroidManifest.xml"
DEFAULT_META_NETWORK_SECURITY_CONFIG = (
    DEFAULT_EXTENSION_DIR / "res/android/res/xml/meta_network_security_config.xml"
)
DEFAULT_SMAATO_NETWORK_SECURITY_CONFIG = (
    DEFAULT_EXTENSION_DIR / "res/android/res/xml/smaato_network_security_config.xml"
)


def condition(key: str) -> str:
    return f"levelplay.{key}_android"


def render_gradle(catalog: dict[str, Any]) -> str:
    lines = [
        "// Generated by updater/android.py from updater/networks.json.",
        "// Run `python3 updater/android.py check` in CI.",
        "",
        "repositories {",
        "    google()",
        "    mavenCentral()",
    ]

    for key in ANDROID_KEYS:
        android = catalog["networks"][key]["android"]
        for repository in android.get("repositories", []):
            if repository == "google":
                continue
            lines.append(f"    {{{{#{condition(key)}}}}}")
            lines.append(f"    maven {{ url '{repository}' }}")
            lines.append(f"    {{{{/{condition(key)}}}}}")

    lines.extend(("}", "", "dependencies {"))
    levelplay_android = catalog["levelplay"]["android"]
    lines.append(f"    implementation '{levelplay_android['coordinate']}'")
    lines.append("    implementation fileTree(dir: 'libs', include: ['*.jar'])")
    for dependency in levelplay_android["dependencies"]:
        if dependency.startswith("com.google.android.gms:"):
            lines.append("    {{#levelplay.android_google_identifiers}}")
            lines.append(f"    implementation '{dependency}'")
            lines.append("    {{/levelplay.android_google_identifiers}}")
        else:
            lines.append(f"    implementation '{dependency}'")

    for key in ANDROID_KEYS:
        network = catalog["networks"][key]
        android = network["android"]
        lines.extend(
            (
                "",
                f"    {{{{#{condition(key)}}}}}",
                f"    // {network['display_name']}",
                f"    implementation '{android['adapter']}'",
            )
        )
        for dependency in android.get("dependencies", []):
            lines.append(f"    implementation '{dependency}'")
        lines.append(f"    {{{{/{condition(key)}}}}}")

    lines.extend(("}", ""))
    return "\n".join(lines)


def render_manifest() -> str:
    return """<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by updater/android.py from updater/networks.json. -->
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="{{android.package}}">

    <uses-sdk
        android:minSdkVersion="{{android.minimum_sdk_version}}"
        android:targetSdkVersion="{{android.target_sdk_version}}" />

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
{{#levelplay.android_google_identifiers}}
    <uses-permission android:name="com.google.android.gms.permission.AD_ID" />
{{/levelplay.android_google_identifiers}}
{{^levelplay.android_google_identifiers}}
    <uses-permission
        android:name="com.google.android.gms.permission.AD_ID"
        tools:node="remove" />
{{/levelplay.android_google_identifiers}}
{{#levelplay.aps_android}}
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
{{/levelplay.aps_android}}

    <application
{{#levelplay.smaato_android}}
        android:networkSecurityConfig="@xml/smaato_network_security_config"
{{/levelplay.smaato_android}}
{{^levelplay.smaato_android}}
{{#levelplay.meta_android}}
        android:networkSecurityConfig="@xml/meta_network_security_config"
{{/levelplay.meta_android}}
{{/levelplay.smaato_android}}
        >
{{#levelplay.aps_android}}
        <activity
            android:name="com.amazon.device.ads.DTBInterstitialActivity"
            android:exported="false" />
        <activity
            android:name="com.amazon.device.ads.DTBAdActivity"
            android:exported="false" />
{{/levelplay.aps_android}}
    </application>
</manifest>
"""


def render_meta_network_security_config() -> str:
    return """<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">127.0.0.1</domain>
    </domain-config>
</network-security-config>
"""


def render_smaato_network_security_config() -> str:
    return """<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <base-config cleartextTrafficPermitted="true" />
</network-security-config>
"""


def generate_or_check(args: argparse.Namespace, check: bool) -> int:
    catalog = load_catalog()
    results = (
        write_or_check(args.gradle, render_gradle(catalog), check),
        write_or_check(args.manifest, render_manifest(), check),
        write_or_check(
            args.meta_network_security_config,
            render_meta_network_security_config(),
            check,
        ),
        write_or_check(
            args.smaato_network_security_config,
            render_smaato_network_security_config(),
            check,
        ),
    )
    return 0 if all(results) else 1


def validate_coordinate(
    coordinate: str,
    repository: str,
    timeout: float,
    require_latest: bool,
) -> bool:
    _, artifact, pinned = parse_coordinate(coordinate)
    release, versions = maven_versions(coordinate, repository, timeout)
    if pinned not in versions:
        print(
            f"missing: {coordinate} is not published in {repository}",
            file=sys.stderr,
        )
        return False
    if require_latest and release != pinned:
        print(
            f"outdated: {coordinate} (repository release is {release or 'unknown'})",
            file=sys.stderr,
        )
        return False
    suffix = " (current release)" if release == pinned else ""
    print(f"verified: {artifact}:{pinned}{suffix}")
    return True


def refresh(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    source = catalog["sources"]["android_mediation_matrix"]
    print(f"Unity compatibility matrix: {source}")

    base = catalog["levelplay"]["android"]["coordinate"]
    ok = validate_coordinate(base, MAVEN_CENTRAL, args.timeout, True)
    for dependency in catalog["levelplay"]["android"]["dependencies"]:
        repository = dependency_repository(dependency, ("google",))
        ok = (
            validate_coordinate(dependency, repository, args.timeout, False)
            and ok
        )

    for key in ANDROID_KEYS:
        android = catalog["networks"][key]["android"]
        ok = (
            validate_coordinate(
                android["adapter"], MAVEN_CENTRAL, args.timeout, True
            )
            and ok
        )
        repositories = android.get("repositories", [])
        for dependency in android.get("dependencies", []):
            repository = dependency_repository(dependency, repositories)
            ok = (
                validate_coordinate(
                    dependency, repository, args.timeout, False
                )
                and ok
            )

    if ok:
        print("Android catalog metadata is valid.")
        return 0
    print(
        "Android catalog validation failed. Reconcile versions with the Unity "
        "compatibility matrix before editing updater/networks.json.",
        file=sys.stderr,
    )
    return 1


def add_output_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--gradle",
        type=Path,
        default=DEFAULT_GRADLE,
        help=f"build.gradle output (default: {DEFAULT_GRADLE})",
    )
    parser.add_argument(
        "--manifest",
        type=Path,
        default=DEFAULT_MANIFEST,
        help=f"AndroidManifest.xml output (default: {DEFAULT_MANIFEST})",
    )
    parser.add_argument(
        "--meta-network-security-config",
        type=Path,
        default=DEFAULT_META_NETWORK_SECURITY_CONFIG,
        help=(
            "Meta network security config output "
            f"(default: {DEFAULT_META_NETWORK_SECURITY_CONFIG})"
        ),
    )
    parser.add_argument(
        "--smaato-network-security-config",
        type=Path,
        default=DEFAULT_SMAATO_NETWORK_SECURITY_CONFIG,
        help=(
            "Smaato network security config output "
            f"(default: {DEFAULT_SMAATO_NETWORK_SECURITY_CONFIG})"
        ),
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog=(
            "Compatibility aliases: --generate, --check, and --refresh map to "
            "the corresponding commands."
        ),
    )
    commands = parser.add_subparsers(dest="command", required=True)

    generate_parser = commands.add_parser(
        "generate", help="generate deterministic Android manifests"
    )
    add_output_arguments(generate_parser)

    check_parser = commands.add_parser(
        "check", help="diff checked-in Android manifests against generated output"
    )
    add_output_arguments(check_parser)

    refresh_parser = commands.add_parser(
        "refresh", help="validate pinned artifacts against live Maven metadata"
    )
    refresh_parser.add_argument(
        "--timeout",
        type=float,
        default=20.0,
        help="per-request network timeout in seconds (default: 20)",
    )
    return parser


def normalize_compatibility_aliases(argv: Sequence[str]) -> list[str]:
    values = list(argv)
    aliases = {
        "--generate": "generate",
        "--check": "check",
        "--refresh": "refresh",
    }
    if values and values[0] in aliases:
        values[0] = aliases[values[0]]
    return values


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    values = normalize_compatibility_aliases(
        sys.argv[1:] if argv is None else argv
    )
    args = parser.parse_args(values)
    try:
        if args.command == "generate":
            return generate_or_check(args, False)
        if args.command == "check":
            return generate_or_check(args, True)
        return refresh(args)
    except UpdaterError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
