#!/usr/bin/env python3

"""Generate and validate the Defold iOS LevelPlay manifests."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
from typing import Any, Sequence

from common import (
    DEFAULT_EXTENSION_DIR,
    IOS_KEYS,
    UpdaterError,
    cocoa_latest_spec,
    load_catalog,
    write_or_check,
)


DEFAULT_PODFILE = DEFAULT_EXTENSION_DIR / "manifests/ios/Podfile"
DEFAULT_INFO_PLIST = DEFAULT_EXTENSION_DIR / "manifests/ios/Info.plist"

# These are the current official CocoaPods product identifiers. CocoaPods
# identifiers cannot be replaced by the public LevelPlay product name.
LEVELPLAY_SDK_POD = "IronSourceSDK"
AD_QUALITY_POD = "IronSourceAdQualitySDK"
ADAPTER_PODS = {
    "applovin": "IronSourceAppLovinAdapter",
    "aps": "IronSourceAPSAdapter",
    "bidmachine": "IronSourceBidMachineAdapter",
    "bigo": "IronSourceBigoAdapter",
    "chartboost": "IronSourceChartboostAdapter",
    "dt_exchange": "IronSourceFyberAdapter",
    "admob": "IronSourceAdMobAdapter",
    "hyprmx": "IronSourceHyprMXAdapter",
    "inmobi": "IronSourceInMobiAdapter",
    "liftoff": "IronSourceVungleAdapter",
    "line": "IronSourceLineAdapter",
    "meta": "IronSourceFacebookAdapter",
    "mintegral": "IronSourceMintegralAdapter",
    "mobilefuse": "IronSourceMobileFuseAdapter",
    "moloco": "IronSourceMolocoAdapter",
    "ogury": "IronSourceOguryAdapter",
    "pangle": "IronSourcePangleAdapter",
    "pubmatic": "LevelPlayPubMaticAdapter",
    "smaato": "IronSourceSmaatoAdapter",
    "superawesome": "IronSourceSuperAwesomeAdapter",
    "unity_ads": "IronSourceUnityAdsAdapter",
    "verve": "IronSourceVerveAdapter",
    "vk": "IronSourceMyTargetAdapter",
    "yandex": "IronSourceYandexAdapter",
    "yso": "IronSourceYSOAdapter",
    "tencent": "IronSourceTencentAdapter",
}


def condition(key: str) -> str:
    return f"levelplay.{key}_ios"


def render_podfile(catalog: dict[str, Any]) -> str:
    minimum_version = catalog["levelplay"]["ios"]["minimum_version"]
    sdk_version = catalog["levelplay"]["ios"]["version"]
    lines = [
        "# Generated by updater/ios.py from updater/networks.json.",
        "# Run `python3 updater/ios.py check` in CI.",
        f"platform :ios, '{minimum_version}'",
        "",
        f"pod '{LEVELPLAY_SDK_POD}', '{sdk_version}'",
        (
            f"pod '{AD_QUALITY_POD}', "
            f"'{catalog['levelplay']['ios']['ad_quality_version']}'"
        ),
    ]

    for key in IOS_KEYS:
        network = catalog["networks"][key]
        version = network["ios"]["adapter_version"]
        lines.extend(
            (
                "",
                f"{{{{#{condition(key)}}}}}",
                f"# {network['display_name']}",
                f"pod '{ADAPTER_PODS[key]}', '{version}'",
                f"{{{{/{condition(key)}}}}}",
            )
        )

    lines.append("")
    return "\n".join(lines)


def skadnetwork_lines(catalog: dict[str, Any]) -> list[str]:
    lines: list[str] = []
    for identifier in catalog["levelplay"]["ios"]["skadnetwork_ids"]:
        lines.append(
            "            <dict><key>SKAdNetworkIdentifier</key>"
            f"<string>{identifier}</string></dict>"
        )

    for key in IOS_KEYS:
        identifiers = catalog["networks"][key]["ios"].get("skadnetwork_ids", [])
        if not identifiers:
            continue
        lines.append(f"{{{{#{condition(key)}}}}}")
        for identifier in identifiers:
            lines.append(
                "            <dict><key>SKAdNetworkIdentifier</key>"
                f"<string>{identifier}</string></dict>"
            )
        lines.append(f"{{{{/{condition(key)}}}}}")

    return lines


def render_info_plist(catalog: dict[str, Any]) -> str:
    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" '
        '"http://www.apple.com/DTDs/PropertyList-1.0.dtd" '
        '[ <!ATTLIST key merge (keep) #IMPLIED> ]>',
        "<!-- Generated by updater/ios.py from updater/networks.json. -->",
        "<!-- The catalog contains Unity's primary SKAdNetwork IDs. Add the -->",
        "<!-- app/network-specific partner IDs linked from Unity's manual. -->",
        '<plist version="1.0">',
        "    <dict>",
        "        <key merge='keep'>SKAdNetworkItems</key>",
        "        <array>",
        *skadnetwork_lines(catalog),
        "        </array>",
        "",
        "        <key>NSAppTransportSecurity</key>",
        "        <dict>",
        "            <key>NSAllowsArbitraryLoads</key>",
        "            <true/>",
        "        </dict>",
        "",
        "{{#levelplay.admob_ios}}",
        "        <key>GADApplicationIdentifier</key>",
        "        <string>{{levelplay.admob_ios_appid}}</string>",
        "{{/levelplay.admob_ios}}",
        "",
        "        <key>NSUserTrackingUsageDescription</key>",
        "        <string>{{levelplay.ios_tracking_usage_description}}</string>",
        "",
        "        <key>NSAdvertisingAttributionReportEndpoint</key>",
        "        <string>https://postbacks-is.com/</string>",
        "",
        "{{#levelplay.hyprmx_ios}}",
        "        <key>NSCameraUsageDescription</key>",
        "        <string>{{project.title}} requests access to the camera.</string>",
        "        <key>NSPhotoLibraryAddUsageDescription</key>",
        "        <string>{{project.title}} requests permission to save photos.</string>",
        "{{/levelplay.hyprmx_ios}}",
        "    </dict>",
        "</plist>",
        "",
    ]
    return "\n".join(lines)


def generate_or_check(args: argparse.Namespace, check: bool) -> int:
    catalog = load_catalog()
    results = (
        write_or_check(args.podfile, render_podfile(catalog), check),
        write_or_check(args.info_plist, render_info_plist(catalog), check),
    )
    return 0 if all(results) else 1


def validate_pod(
    pod: str, pinned_version: str, timeout: float
) -> bool:
    spec = cocoa_latest_spec(pod, timeout)
    latest_version = str(spec.get("version", ""))
    if latest_version != pinned_version:
        print(
            f"outdated: {pod} {pinned_version} "
            f"(CocoaPods trunk latest is {latest_version or 'unknown'})",
            file=sys.stderr,
        )
        return False
    print(f"verified: {pod}:{pinned_version}")
    return True


def refresh(args: argparse.Namespace) -> int:
    catalog = load_catalog()
    source = catalog["sources"]["ios_mediation_matrix"]
    print(f"Unity compatibility matrix: {source}")

    ok = validate_pod(
        LEVELPLAY_SDK_POD,
        catalog["levelplay"]["ios"]["version"],
        args.timeout,
    )
    ok = validate_pod(
        AD_QUALITY_POD,
        catalog["levelplay"]["ios"]["ad_quality_version"],
        args.timeout,
    ) and ok
    for key in IOS_KEYS:
        version = catalog["networks"][key]["ios"]["adapter_version"]
        ok = validate_pod(ADAPTER_PODS[key], version, args.timeout) and ok

    if ok:
        print("iOS catalog metadata is valid.")
        return 0
    print(
        "iOS catalog validation failed. Reconcile versions with the Unity "
        "compatibility matrix before editing updater/networks.json.",
        file=sys.stderr,
    )
    return 1


def add_output_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--podfile",
        type=Path,
        default=DEFAULT_PODFILE,
        help=f"Podfile output (default: {DEFAULT_PODFILE})",
    )
    parser.add_argument(
        "--info-plist",
        type=Path,
        default=DEFAULT_INFO_PLIST,
        help=f"Info.plist output (default: {DEFAULT_INFO_PLIST})",
    )


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description=__doc__,
        epilog=(
            "Compatibility aliases: --generate, --check, and --refresh map to "
            "the corresponding commands."
        ),
    )
    commands = parser.add_subparsers(dest="command", required=True)

    generate_parser = commands.add_parser(
        "generate", help="generate deterministic iOS manifests"
    )
    add_output_arguments(generate_parser)

    check_parser = commands.add_parser(
        "check", help="diff checked-in iOS manifests against generated output"
    )
    add_output_arguments(check_parser)

    refresh_parser = commands.add_parser(
        "refresh",
        help="validate pinned SDK and adapters against live CocoaPods metadata",
    )
    refresh_parser.add_argument(
        "--timeout",
        type=float,
        default=20.0,
        help="per-request network timeout in seconds (default: 20)",
    )
    return parser


def normalize_compatibility_aliases(argv: Sequence[str]) -> list[str]:
    values = list(argv)
    aliases = {
        "--generate": "generate",
        "--check": "check",
        "--refresh": "refresh",
    }
    if values and values[0] in aliases:
        values[0] = aliases[values[0]]
    return values


def main(argv: Sequence[str] | None = None) -> int:
    parser = build_parser()
    values = normalize_compatibility_aliases(
        sys.argv[1:] if argv is None else argv
    )
    args = parser.parse_args(values)
    try:
        if args.command == "generate":
            return generate_or_check(args, False)
        if args.command == "check":
            return generate_or_check(args, True)
        return refresh(args)
    except UpdaterError as error:
        print(f"error: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
