name: Update version of the extension in a file

on:
  release:
    types:
      - published

jobs:
  update_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Update version in ext.properties
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          files: 'extension-ironsource/ext.properties'
          find: 'version.default = \d+\.\d+\.\d+'
          replace: 'version.default = ${{ github.event.release.tag_name }}'

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Update tag
        uses: richardsimko/update-tag@v1.0.7
        with:
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
